[config]
environment = "mainnet"

[packages]
kai_sav = { local = "../../../../../move/kai/sav/core" }
sui = { system = "sui" }
std = { system = "std" }
cetus_clmm = { local = "../../../../../move/_vendor/Cetus/clmm-v14" }
cetus_integrate = { local = "../../../../../move/_vendor/Cetus/integrate-v15" }
integer_mate = { local = "../../../../../move/_vendor/Cetus/integer-mate-v7", override = true }
kai_leverage = { local = "../../../../../move/kai/leverage/core" }
kai_leverage_util = { local = "../../../../../move/kai/leverage/util" }
pyth = { local = "../../../../../move/_vendor/Pyth/pro-compatible-v1" }
wormhole = { local = "../../../../../move/_vendor/Pyth/wormhole-simple-majority-v1" }
bluefin_spot = { local = "../../../../../move/_vendor/Bluefin/spot-v17" }
